### ISSUE TITLE
FYI looks like GabrielBB/xvfb-action includes this

### ISSUE THREAD

**Issue by webknjaz** [bcomnes/cleanup-xvfb#20]
https://github.com/GabrielBB/xvfb-action/blob/master/cleanup.sh

**Comment by bcomnes** [comment]
looks legit yeah?

**Comment by webknjaz** [comment]
Yep, I tested it out. Just wanted to notify you as it's probably better to focus the effort on that action.

**Comment by bcomnes** [comment]
Cool yeah glad the script was useful. Looks like they are adding a few more features. This is used in a few places allready, and basically feature complete. Not even sure if it's needed any longer tbh, was an issue with early action runners. Thanks for the heads up.  Closing for now.
