### ISSUE TITLE
Update to node@16.

### ISSUE THREAD

**Issue by duhrer** [bcomnes/cleanup-xvfb#54]
First, thanks for this useful action.

In recent CI runs, I've started seeing warnings for this action related to [this effort from GitHub](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).  In short, they're urging everyone to move on from node@12 to a currently supported version, which would mean updating to node@16.

Happy to prepare a pull with the very minimal changes if you like.

**Comment by bcomnes** [comment]
Sorry about that. Action maintained is set to autopilot but there is no dependabot setting for action version unfortunately. I'll get a release out.

**Comment by bcomnes** [comment]
Cool, I took care of the release, but it looks like my example script os broken, and I'm not going to maintain nanochorome anymore. 

If you are looking for a contribution and you have a better example of puppeteer or playwright or something that can use this action, PR an updated example and I will land it. Benefit to you would be this action tracking maintenance targets close to end user use cases. 

Have a good one!

**Comment by duhrer** [comment]
Thanks so much for the quick response and for maintaining the action.  We don't have any better examples at the moment, but if I see anything, I'll comment here.
